// js/react/contextual-comments-canvas/src/App.jsx
import { SuperVizRoomProvider } from "@superviz/react-sdk";
import CanvasCommentsImplementation from "./components/CanvasCommentsImplementation";

const DEVELOPER_KEY = import.meta.env.VITE_DEVELOPER_KEY;
const participant = Math.floor(Math.random() * 10);
const groupId = "sv-sample-room-react-js-comments-canvas";
const groupName = "Sample Room for Contextual Comments Canvas (React/JS)";

function App() {
  return (
    <SuperVizRoomProvider
      developerKey={DEVELOPER_KEY}
      group={{
        id: groupId,
        name: groupName,
      }}
      participant={{
        id: participant.toString(),
        name: "John " + participant,
      }}
      roomId={groupId}
    >
      <CanvasCommentsImplementation />
    </SuperVizRoomProvider>
  );
}

export default App;

// js/vue/video-conference/src/App.vue
<template>
  <button :disabled="isRunning" @click="initSuperVizRoom">Join Video Conference</button>
</template>

<script lang="js">
import { defineComponent, ref } from 'vue';
import { v4 as uuidv4 } from "uuid";
import SuperVizRoom from "@superviz/sdk";
import { VideoConference } from "@superviz/sdk/lib/components";

const groupId = "sv-sample-room-vue-js-video-conference";
const groupName = "Sample Room for Video Conference (Vue/JS)";
const DEVELOPER_KEY = process.env.VUE_APP_SUPERVIZ_DEVELOPER_TOKEN;


export default defineComponent({
  name: 'App',
  setup() {
    const isRunning = ref(false);

    const initSuperVizRoom = async () => {
      isRunning.value = true;
      const roomId = uuidv4();
      const room = await SuperVizRoom(DEVELOPER_KEY, {
        roomId: roomId,
        group: {
          id: groupId,
          name: groupName,
        },
        participant: {
          id: "zeus",
          name: "Zeus",
        },

      });

      const video = new VideoConference({
        participantType: "host",
      });

      room.addComponent(video);
    };

    return {
      isRunning,
      initSuperVizRoom,
    };
  }
});
</script>
