// ts/react/who-is-online/src/components/WhoIsOnlineContainer.tsx
import SuperVizRoom from "@superviz/sdk";
import { WhoIsOnline } from "@superviz/sdk/lib/components";

const groupId = "sv-sample-room-react-ts-who-is-online";
const groupName = "Sample Room for Who-is-Online (React/TS)";
const DEVELOPER_KEY = import.meta.env.VITE_DEVELOPER_KEY;

const initWhoIsOnline = async (roomId: string, userId: string, name: string, containerId: string) => {
  const room = await SuperVizRoom(DEVELOPER_KEY, {
    roomId: roomId,
    group: {
      id: groupId,
      name: groupName,
    },
    participant: {
      id: userId,
      name: name,
    },
    environment: "dev" as any,
  });

  const whoIsOnline = new WhoIsOnline(containerId);
  room.addComponent(whoIsOnline);
};

export default function WhoIsOnlineContainer({ name, roomId }: { name: string; roomId: string }) {
  const containerId = name + "-container";
  const userId = name.toLowerCase();

  return (
    <section>
      <button onClick={() => initWhoIsOnline(roomId, userId, name, containerId)}>
        Enter Who-is-Online as "{name}"
      </button>
      <div id={containerId} />
    </section>
  );
}

// js/vue/who-is-online/src/components/WhoIsOnlineContainer.vue
<template>
  <section>
    <button @click="initWhoIsOnline">
        Enter Who-is-Online as {{ participantName }}
      </button>
    <div :id="containerId" />
  </section>
</template>
  
<script>
  import SuperVizRoom from "@superviz/sdk";
  import { WhoIsOnline } from "@superviz/sdk/lib/components";

  import { ref, defineComponent } from "vue";
  
  const groupId = "sv-sample-room-vue-js-who-is-online";
  const groupName = "Sample Room for Who Is Online (Vue/JS)";

  const DEVELOPER_KEY = process.env.VUE_APP_SUPERVIZ_DEVELOPER_TOKEN;
  
  export default defineComponent({
    name: 'WhoIsOnlineContainer',
    props: {
      participantName: {
        type: String,
        required: true,
      },
      roomId: {
        type: String,
        required: true,
      },
    },
    setup(props) {
      const containerId = ref(props.participantName + "-container");
      const userId = ref(props.participantName.toLowerCase());
      const loaded = ref(false);
      
      async function initWhoIsOnline() {
        const room = await SuperVizRoom(DEVELOPER_KEY, {
          roomId: props.roomId,
          group: {
            id: groupId,
            name: groupName,
          },
          participant: {
            id: userId.value,
            name: props.participantName,
          },
          environment: "dev",
        });
  
        const mousePointer = new WhoIsOnline(containerId.value);
        room.addComponent(mousePointer);
      }
  
      return {
        containerId,
        initWhoIsOnline,
      };
    },
  });
  </script>
