// src/App.tsx
import { useRef } from "react";
import WhoIsOnlineContainer from "./components/WhoIsOnlineContainer";
import { v4 as uuidv4 } from "uuid";

function App() {
  const roomId = useRef(uuidv4()).current;

  // We are initializing multiple rooms for demo purposes.
  return (
    <main>
        <WhoIsOnlineContainer name="Zeus" roomId={roomId} />
        <WhoIsOnlineContainer name="Hera" roomId={roomId} />
        <WhoIsOnlineContainer name="Apollo" roomId={roomId} />
        <WhoIsOnlineContainer name="Artemis" roomId={roomId} />
        <WhoIsOnlineContainer name="Dionysus" roomId={roomId} />
        <WhoIsOnlineContainer name="Athena" roomId={roomId} />
    </main>
  );
}

export default App;

// ts/vue/who-is-online/src/App.vue
<template>
  <main>
    <!-- We are initializing multiple rooms for demo purposes. -->
    <who-is-online-container participantName="Zeus" :roomId="roomId"/>
    <who-is-online-container participantName="Hera" :roomId="roomId"/>
    <who-is-online-container participantName="Apollo" :roomId="roomId"/>
    <who-is-online-container participantName="Artemis" :roomId="roomId"/>
    <who-is-online-container participantName="Dionysus" :roomId="roomId"/>
    <who-is-online-container participantName="Athena" :roomId="roomId"/>
  </main>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

import WhoIsOnlineContainer from './components/WhoIsOnlineContainer.vue';

import { v4 as uuidv4 } from "uuid";


export default defineComponent({
  name: 'App',
  components: { WhoIsOnlineContainer }, 
  setup() {
    const roomId = ref(uuidv4()).value;

    return {
      roomId,
    };
  }
});
</script>
