// js/react/contextual-comments-autodesk/src/App.jsx
import { SuperVizRoomProvider } from "@superviz/react-sdk";

import AutodeskCommentsImplementation from "./components/AutodeskCommentsImplementation";

const DEVELOPER_KEY = import.meta.env.VITE_DEVELOPER_KEY;
const groupId = "sv-sample-room-react-js-autodesk-contextual-comments";
const groupName = "Sample Room for Autodesk Contextual Comments (React/JS)";
const participant = Math.floor(Math.random() * 100);

function App() {
  return (
    <SuperVizRoomProvider
      developerKey={DEVELOPER_KEY}
      group={{
        id: groupId,
        name: groupName,
      }}
      participant={{
        id: participant.toString(),
        name: "John " + participant,
      }}
      roomId={groupName}
    >
      <AutodeskCommentsImplementation />
    </SuperVizRoomProvider>
  );
}

export default App;

// src/App.vue
<template>
  <button :disabled="isRunning" @click="initSuperVizRoom">Join Video Conference</button>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import { v4 as uuidv4 } from "uuid";
import SuperVizRoom from "@superviz/sdk";
import { VideoConference } from "@superviz/sdk/lib/components";

const groupId = "sv-sample-room-vue-t s-video-conference";
const groupName = "Sample Room for Video Conference (Vue/TS)";
const DEVELOPER_KEY = process.env.VUE_APP_SUPERVIZ_DEVELOPER_TOKEN as string;

export default defineComponent({
  name: "App",
  setup() {
    const isRunning = ref(false);

    const initSuperVizRoom = async () => {
      isRunning.value = true;
      const roomId = uuidv4();
      const room = await SuperVizRoom(DEVELOPER_KEY, {
        roomId: roomId,
        group: {
          id: groupId,
          name: groupName,
        },
        participant: {
          id: "zeus",
          name: "Zeus",
        },
      });

      const video = new VideoConference({
        participantType: "host",
      });

      room.addComponent(video);
    };

    return {
      isRunning,
      initSuperVizRoom,
    };
  },
});
</script>
