// src/App.tsx
import { useRef } from 'react'
import Canvas from './components/Canvas'
import { v4 as uuidv4 } from 'uuid'

function App() {
  const roomId = useRef(uuidv4()).current

  // We are initializing two rooms for demo purposes.
  return (
    <>
      <Canvas name="Zeus" roomId={roomId}/>
      <Canvas name="Hera" roomId={roomId}/>
    </>
  )
}

export default App

// js/vue/mouse-pointers/src/App.vue
<template>
  <mouse-canvas participantName="Zeus" :roomId="roomId"/>
  <mouse-canvas participantName="Hera" :roomId="roomId"/>
</template>

<script>
import { defineComponent, ref } from 'vue';

import MouseCanvas from './components/MouseCanvas.vue';

import { v4 as uuidv4 } from "uuid";


export default defineComponent({
  name: 'App',
  components: { MouseCanvas }, 
  setup() {
    const roomId = ref(uuidv4()).value;

    return {
      roomId,
    };
  }
});
</script>
